# Generated by Django 3.0.3 on 2020-09-12 12:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publist_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 3, 4, 300344, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 3, 4, 300344, tzinfo=utc)),
        ),
    ]
