# Generated by Django 3.0.3 on 2020-09-12 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200912_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 23, 1, 332298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 23, 1, 332298, tzinfo=utc)),
        ),
    ]
